# Required metadata
sonar.projectKey=fuel-consumption
sonar.projectName=Fuel-Consumption
sonar.projectVersion=1.0

# Path to sources
sonar.sources=src/main/java
sonar.java.binaries=target/classes

# URL of your Docker SonarQube server
sonar.host.url=http://localhost:9000

# Optional: authentication token (strongly recommended for non-local scans)
# You can generate a token in http://localhost:9000 -> My Account -> Security
sonar.token=pat