pipeline {
    agent any

    tools {
        maven "Maven3"
    }

    environment {
        PATH = "/opt/homebrew/bin:/Applications/Docker.app/Contents/Resources/bin:${env.PATH}"
        DOCKERHUB_CREDENTIALS_ID = 'docker-pat'
        DOCKERHUB_REPO = 'leevivl/metropolia-fuel-consumption'
        DOCKER_IMAGE_TAG = 'latest'

        SSH_KEY_PATH = '~/.ssh/leevivl-875.pem'
        REMOTE_USER = 'leevivl'
        REMOTE_HOST = 'shell.metropolia.fi'
        REMOTE_PATH = '/home1-2/l/leevivl/public_html/fuel-consumption-jacoco'
    }

    stages {

        stage('Build and Test') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('Code coverage') {
            steps {
                sh 'mvn jacoco:report'
            }
        }

        stage('Public Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'

                sh "chmod 600 ${SSH_KEY_PATH}"
                sh "scp -i ${SSH_KEY_PATH} -o StrictHostKeyChecking=no -r target/site ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH}"
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh """
                        sonar-scanner \
                        -Dsonar.projectKey=fuel-consumption \
                        -Dsonar.sources=src/main/java
                    """
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: DOCKERHUB_CREDENTIALS_ID,
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        set -e

                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                        docker build -t ${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG} .
                        docker push ${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}
                    '''
                }
            }
        }
    }
}